- src/it/first/pom.xml
- src/it/first/src/test/java/it/EndpointIT.java
> Add endpoint ping to first IT

- src/main/java/boost/project/PackageSpringBootAppWithLibertyMojo.java
> Detect spring boot dependency version

- src/it/pom.xml
- src/it/test15Explicit/pom.xml
- src/it/test15Explicit/src/test/java/it/FeatureVersionIT.java
- src/it/test15Implicit/pom.xml
- src/it/test15Implicit/src/test/java/it/FeatureVersionIT.java
- src/it/test20Implicit/pom.xml
- src/it/test20Implicit/src/test/java/it/FeatureVersionIT.java
Going to replace PR #25 with this, since this merges in an additional change, making the artifact name the same as the subdir names:  **test15Explicit**, **test15Implicit**, etc.
> Fixes #24; add IT-level POM, synch artifact and subdir names

- pom.xml
- src/it/test15Explicit/pom.xml
- src/it/test15Implicit/pom.xml
- src/main/java/boost/project/PackageSpringBootAppWithLibertyMojo.java
> Implemented flexible runtime configuration

- boost-maven-plugin/src/main/java/io/openliberty/boost/docker/AbstractDockerMojo.java
- boost-maven-plugin/src/main/java/io/openliberty/boost/docker/DockerBuildMojo.java
- boost-maven-plugin/src/main/java/io/openliberty/boost/docker/Dockerize.java
- boost-maven-plugin/src/main/java/io/openliberty/boost/docker/MavenSettingsAuthSupplier.java
> Refactor and maintain consistancy in logging

- boost-maven-plugin/src/main/java/io/openliberty/boost/liberty/AbstractLibertyMojo.java
runtimeArtifact should be configurable and not readonly.
> Remove readonly attribute from runtimeArtifact

- boost-maven-plugin/src/it/test-docker/src/test/java/application/DockerPushIT.java
for issue #85
Do not assume the first image in the list of docker images to be the final built image. It can be an intermediate image produced by multi-stage build.
> Refactor tests for docker-push

- Tutorial.md
Add a basic tutorial on how to use Boost to package an existing Spring Boot application and to build a Docker image from it.
> Add basic tutorial doc

- README.md
Add a new "Try it!" section which shows the one-line mvn command to build the uber jar and one for the Docker image. Additionally, add in a Quick Start section of Docker. The tutorial provides more guided flows.
> Update the README w/ "Try it!" and quick start - docker

- boost-maven-plugin/pom.xml
- boost-maven-plugin/src/main/java/io/openliberty/boost/docker/DockerBuildMojo.java
- other-legal/README.md
- other-legal/license-of-works-derived-from/LICENSE-2.0.txt
> Replace copyright with Spotify copyright with ASL 2

- boost-maven-plugin/src/main/java/io/openliberty/boost/liberty/LibertyPackageMojo.java
- boost-maven-plugin/src/main/java/io/openliberty/boost/utils/MavenProjectUtil.java
Fixes #105. Depends on https://github.com/OpenLiberty/boost-common/pull/13.
> Fixes #105

- boost-maven-plugin/src/main/java/io/openliberty/boost/liberty/LibertyPackageMojo.java
This should work now after https://github.com/WASdev/ci.common/pull/21 was merged.
> Remove acceptLicense for WLP and OL features 

- Tutorial.md
The multistage build is supported in Docker 17.05 or higher.
> Add Docker version

- boost-maven-plugin/pom.xml
- boost-maven-plugin/src/it/test-spring-boot-1.5-implicit/invoker.properties
- boost-maven-plugin/src/main/java/io/openliberty/boost/docker/DockerBuildMojo.java
- boost-maven-plugin/src/main/java/io/openliberty/boost/liberty/AbstractLibertyMojo.java
> 133 fix docker build with classifier

- boost-common/src/main/java/io/openliberty/boost/utils/ConfigConstants.java
- boost-common/src/main/java/io/openliberty/boost/utils/LibertyServerConfigGenerator.java
- boost-maven/boost-maven-plugin/src/it/test-jaxrs-2.0/src/test/java/it/EndpointIT.java
- boost-maven/boost-maven-plugin/src/it/test-jaxrs-2.1/src/test/java/it/EndpointIT.java
- boost-maven/boost-maven-plugin/src/main/java/io/openliberty/boost/liberty/LibertyPackageMojo.java
- boost-maven/boost-maven-plugin/src/main/java/io/openliberty/boost/utils/MavenProjectUtil.java
> Context Root and Loose App support

- README.md
Added a bit of help for local development, thanks to @anjumfatima90 for the advice!
> Add a section for the local development dependencies

- boost-common/src/main/java/io/openliberty/boost/common/config/LibertyServerConfigGenerator.java
- boost-common/src/main/java/io/openliberty/boost/common/utils/BoostUtil.java
- boost-common/src/main/java/io/openliberty/boost/common/utils/LibertyBoosterUtil.java
- boost-common/src/main/java/io/openliberty/boost/common/utils/SpringBootUtil.java
- boost-common/src/test/java/io/openliberty/boost/common/config/LibertyServerConfigGeneratorTest.java
- boost-gradle/build.gradle
- boost-gradle/src/main/groovy/io/openliberty/boost/gradle/tasks/BoostPackageTask.groovy
- boost-maven/boost-maven-plugin/src/it/test-jdbc-db2/invoker.properties
- boost-maven/boost-maven-plugin/src/it/test-jdbc-db2/src/test/java/it/Db2PropertiesIT.java
- boost-maven/boost-maven-plugin/src/main/java/io/openliberty/boost/maven/liberty/LibertyPackageMojo.java
- Checking error message for an InvalidPasswordEncodingException
- Refactored LibertyServerConfigGenerator, BoostUtil, SpringBootUtil, and LibertyBoosterUtil to use BoostLoggers
- Added test to check properties written to bootstrap.properties
> Adding check for already encoded DB password

- boost-common/src/main/java/io/openliberty/boost/common/docker/dockerizer/spring/DockerizeLibertySpringBootJar.java
> Updated file permissions during COPY of Spring Boot uber JAR

- boost-maven/README.md
new README removes mention of Liberty or Spring Boot as well as mentions of Docker support (for now)
working on the Tutorial next, but want to get this in for today
> update README for runtime/app agnostic language

- boost-common/src/test/java/io/openliberty/boost/common/boosters/MPConfigBoosterTest.java
- boost-common/src/test/java/io/openliberty/boost/common/boosters/MPHealthBoosterTest.java
- boost-common/src/test/java/io/openliberty/boost/common/boosters/MPOpenTracingBoosterTest.java
- boost-common/src/test/java/io/openliberty/boost/common/boosters/MPRestClientBoosterTest.java
- boost-common/src/test/java/io/openliberty/boost/common/utils/BoosterUtil.java
added unit test to test microprofile and related boosters (cdi and jsonp)
> add mp booster and related unit tests

- .travis.yml
- boost-common/pom.xml
- boost-maven/boost-boosters/booster-cdi-ee8/invoker.properties
- boost-maven/boost-boosters/booster-jaxrs-ee7/invoker.properties
- boost-maven/boost-boosters/booster-jaxrs-ee8/invoker.properties
- boost-maven/boost-boosters/booster-jdbc/invoker.properties
- boost-maven/boost-boosters/booster-jpa-ee7/invoker.properties
- boost-maven/boost-boosters/booster-jpa-ee8/invoker.properties
- boost-maven/boost-boosters/booster-jsonp-ee8/invoker.properties
- boost-maven/boost-boosters/booster-mpConfig-20/invoker.properties
- boost-maven/boost-boosters/booster-mpHealth-20/invoker.properties
- boost-maven/boost-boosters/booster-mpOpenTracing-20/invoker.properties
- boost-maven/boost-boosters/booster-mpRestClient-20/invoker.properties
- boost-maven/boost-maven-plugin/pom.xml
- boost-maven/boost-maven-plugin/src/it/test-dev-release/src/it/dev-project/pom.xml
- boost-maven/boost-maven-plugin/src/it/test-jdbc-db2/pom.xml
- boost-maven/boost-maven-plugin/src/it/test-jdbc/pom.xml
- boost-maven/boost-maven-plugin/src/it/test-spring-boot-docker/pom.xml
- boost-maven/boost-maven-plugin/src/it/test-spring-boot-docker/src/test/java/it/DockerBuildIT.java
- boost-maven/boost-runtimes/runtime-openliberty/invoker.properties
- boost-maven/boost-runtimes/runtime-tomee/invoker.properties
- boost-maven/boost-runtimes/runtime-wlp/invoker.properties
> Delete unnecessary invoker.properties, test Java 11

- boost-maven/boost-maven-plugin/src/main/java/boost/maven/plugin/AbstractMojo.java
- boost-maven/boost-maven-plugin/src/main/java/boost/maven/utils/BoostLogger.java
- boost-maven/boost-runtimes/runtime-openliberty/src/main/java/boost/runtimes/openliberty/LibertyRuntime.java
- boost-maven/boost-runtimes/runtime-tomee/src/main/java/boost/runtimes/tomee/TomeeRuntime.java
> Fix logger to output debug messages at the debug level.

- boost-maven/boost-runtimes/runtime-openliberty/src/main/java/boost/runtimes/openliberty/LibertyRuntime.java
> Update liberty runtime version to 19008

- boost-maven/boost-runtimes/runtime-openliberty/src/main/java/boost/runtimes/openliberty/LibertyRuntime.java
> Change to reflect new package goal configuration parms

- boost-common/src/main/java/boost/common/boosters/JDBCBoosterConfig.java
> Only generate DB config for Derby if no serverName specified

- boost-maven/boost-runtimes/runtime-openliberty/src/main/java/boost/runtimes/openliberty/LibertyRuntime.java
> Use finalName in generated application location in server.xml

- boost-maven/boost-boms/boost-ee7-apis-bom/pom.xml
- boost-maven/boost-boms/boost-ee8-apis-bom/pom.xml
Signed-off-by: Mike Andrasak <andrasak@us.ibm.com>
> Issue 378 validate EE7 and EE8 API levels
